### ISSUE TITLE
Docs: [Question] Should we have consistent sections?

### ISSUE THREAD

**Issue by sympatheticmoose** [grafana/plugin-tools#1008]
We currently have a mixture of behaviours for section pages which may cause confusion for users.  

Sections with content:
- Get started
- Key concepts / Backend plugins
- Migration guides / migrate from AngularJS to React

Sections with indexes (basic lists of items within the section, sometimes with a basic explanation of what the section contains):
- Key concepts
- Tutorials
- How to guides
- How to guides / app plugins
- How to guides / data source plugins
- How to guides / Panel plugins
- How to guides / UI extensions
- Migration guides
- Migration guides / update from grafana versions

Sections with nothing (just expand/collapse):
- E2E test a plugin
- Publish a plugin
- Reference

This has happened as we've gradually expanded sections over time and seen what works, but now that our structure is hopefully starting to settle, we should likely address this inconsistency.

**Comment by josmperez** [comment]
> @josmperez Is this our task and should it stay in our repo/project?

Yes, I'll add this to the roadmap.

**Comment by josmperez** [comment]
I think some additional consistency could potentially improve the user experience, but I don't think we have to be 100% consistent. My preference would be to add indexes to the TOC categories that don't have them, but otherwise leave things the way they are. 

So:
- E2E test a plugin
- Publish a plugin
- Reference
would get indexes.

Any other opinions on this? @sympatheticmoose
