### ISSUE TITLE
Plugins created by tools have front-end errors on older versions of grafana

### ISSUE THREAD

**Issue by sunpe** [grafana/plugin-tools#201]
When I use the latest version of `@grafana/create-plugin` to create a data source plugin, the front end will get an error when adding a data source in an older version of grafana (such as 7.x). Any suggestion?

<img width="931" alt="image" src="https://user-images.githubusercontent.com/8380506/217978297-1dc5b553-8d5c-4edc-8b14-06a43ceab9b9.png">

```[tasklist]

```

**Comment by academo** [comment]
Hi @sunpe 

Create-plugin was created with Grafana 8 and above versions in mind. It is possible to adjust the configuration to make it work with older Grafana versions but for that you can better use the legacy [grafana toolkit](https://github.com/grafana/grafana/blob/main/packages/grafana-toolkit/README.md).

**Comment by jeremypeters** [comment]
I'm getting the same error on Grafana v8.4.4.

**Comment by academo** [comment]
@jeremypeters do you have a repository with the code so I can take a look?

**Comment by jeremypeters** [comment]
@academo No repository I'm afraid - all I did was just go through the @grafana/create-plugin wizard. For my plugin I I have now used [Grafana Toolkit](https://github.com/grafana/grafana/blob/main/packages/grafana-toolkit/README.md) instead.

**Comment by academo** [comment]
@jeremypeters I don't recommend you using grafana-toolkit as we will be dropping support for plugins on the next version.  What I recommend you is:

* make sure you are using the latest version of create plugin

**Comment by academo** [comment]
@jeremypeters I had time to do some further testing of this issue and it seems the problem with the generated datasource is that the `grafana/ui` doesn't offer the `SecureInput` component in Grafana v8 and that's why it fails. If you change the `grafana/ui` package version to your min target version, typescript should tell you what's available and what's not.

I modified (locally) a generated datasource to not use this component and all worked as expected.

We mark the generated plugins by create-tool to be compatible with Grafana 9.3.8 or above (at the moment of writing this comment) and that matches the components we are using in the examples.

Generally speaking the webpack configuration that create-tool generates is compatible with any versions of grafana that supports react plugins (7 and above) but not with angularjs plugins.

I still encourage you to use the tool over toolkit as its supports will be completely removed in Grafana v10. you can migrate your plugin (in case you already went ahead to use toolkit) https://github.com/grafana/plugin-tools/tree/main/packages/create-plugin/#migrate-your-existing-plugin
