### ISSUE TITLE
Bug: adding datasource plugin gives 'plugin unavailable'

### ISSUE THREAD

**Issue by michiel2002v** [grafana/plugin-tools#321]
### Which package(s) does this bug affect?

- [X] Create Plugin
- [ ] Sign Plugin

### Package versions

```shell
Need to install the following packages:
  @grafana/create-plugin@1.9.0
Ok to proceed? (y) y
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
1.9.0
```

### What happened?

I am working with Grafana v7.0.0 for which I want to write a datasource plugin that connects data from an influxdb with data from an azure blob storage. Before writing the code for this, I wanted to test the template by adding it to grafana. When I do this, without adding code, I get the message 'plugin unavailable'. How do I fix this? The build was successful though with the same package warnings (which I feel are not the cause anyway).

### What you expected to happen

I was hoping to add to the plugin so that as I write code, I can see the modifications.

### How to reproduce it (as minimally and precisely as possible)

 just download the template,
create the custom.ini file from grafana with the correct path to your plugin's folder and put it in development mode.

### Environment

```shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 5.69 GB / 7.70 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.0/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  npmPackages:
    @grafana/data: 9.5.3 => 9.5.3
    @grafana/e2e: 9.5.3 => 9.5.3
    @grafana/e2e-selectors: 9.5.3 => 9.5.3
    @grafana/eslint-config: ^6.0.0 => 6.0.0
    @grafana/runtime: 9.5.3 => 9.5.3
    @grafana/tsconfig: ^1.2.0-rc1 => 1.2.0-rc1
    @grafana/ui: 9.5.3 => 9.5.3
```

**Comment by academo** [comment]
Hi @michiel2002v I tested a newly generated datasource plugin in Grafana 7.5.17 and managed to see the plugin available in the list. The plugin didn't work because of the many new API we use in our generated code that is intended for Grafana >9 so I modified it to have an absolute basic code and after that it  worked as expected.

Things to keep in consideration:

* Run `yarn dev` or `yarn build` *before* you start your grafana server. Otherwise grafana won't pick up the `dist` folder.  you only need to do this the very first time you initialize the plugin. If you change anything in your plugin.json you also need to restart your grafana server.
* Check your `grafanaDependency` field in your plugin.json. See that you are not setting a required version higher than the one you target.
